### ISSUE TITLE
Uncaught TypeError: Cannot read property 'langEntries' of null

### ISSUE THREAD

**Issue by prussiap** [galetahub/ckeditor#564]
Hi all,
Knew to ckeditor with rails app. All seemed to be working before but i added some plugins and started geting this langEntries of null. Adding config.setLang didn't seem to do it and plugins.language seems to not be set so clearly i'm doing something wrong.. Perhaps it's loading twice due to the tree but removing the application.js tree_required breaks all sorts of things for me.

Anyway config.js:

```
CKEDITOR.editorConfig = function (config) {
  //config.assets_languages = ['en']
  config.setLang = ('dialog', 'en');
  config.setLang = ('lineutils', 'en');
  config.setLang = ('widget', 'en');
  config.setLang = ('codesnippet', 'en');

  config.extraPlugins = 'dialog';
  config.extraPlugins = 'dialogui';
  config.extraPlugins = 'lineutils';
  config.extraPlugins = 'clipboard';
  config.extraPlugins = 'widget';
  config.extraPlugins = 'codesnippet';
}
```

Application.js

```
//= require jquery
//= require jquery_ujs
//= require twitter/bootstrap
//= require turbolinks
//= require ckeditor/init
//= require_tree .
```

Everything is in the correct folder.. So i'm a bit at a loss.. any thoughts?

Rails 4 also 

Sorry also the javascript errors. Which makes me think dependencies are either included and/or loaded twice for some of these:

```
Uncaught [CKEDITOR.resourceManager.add] The resource name "clipboard" is already registered.CKEDITOR.resourceManager.add @ ckeditor.js?body=1:225(anonymous function) @ plugin.js?body=1:87(anonymous function) @ plugin.js?body=1:1197
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ bg.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ ca.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ cs.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ da.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ de.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ el.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ en-gb.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ en.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ eo.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ es.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ et.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ fa.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ fi.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ fr-ca.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ fr.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ he.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ hr.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ hu.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ it.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ ja.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ km.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ ku.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ lt.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ lv.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ nb.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ nl.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ no.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ pl.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ pt-br.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ pt.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ ro.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ ru.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ sk.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ sl.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ sq.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ sv.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ th.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ tr.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ tt.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ ug.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ uk.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ vi.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ zh-cn.js?body=1:7
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ zh.js?body=1:7
ckeditor.js?body=1:225 Uncaught [CKEDITOR.resourceManager.add] The resource name "dialog" is already registered.CKEDITOR.resourceManager.add @ ckeditor.js?body=1:225(anonymous function) @ plugin.js?body=1:3083
ckeditor.js?body=1:225 Uncaught [CKEDITOR.resourceManager.add] The resource name "dialogui" is already registered.CKEDITOR.resourceManager.add @ ckeditor.js?body=1:225(anonymous function) @ plugin.js?body=1:11
console.js?body=1:13 Uncaught ReferenceError: CKCONSOLE is not defined(anonymous function) @ console.js?body=1:13(anonymous function) @ console.js?body=1:132
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ af.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ ar.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ ca.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ cs.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ cy.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ da.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ de.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ el.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ en-gb.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ en.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ eo.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ es.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ fa.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ fi.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ fr.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ gl.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ he.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ hr.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ hu.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ it.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ ja.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ km.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ ko.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ ku.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ nb.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ nl.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ no.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ pl.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ pt-br.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ pt.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ ru.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ sk.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ sl.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ sq.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ sv.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ tr.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ tt.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ uk.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ vi.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of nullCKEDITOR.plugins.setLang @ ckeditor.js?body=1:229(anonymous function) @ zh-cn.js?body=1:6
ckeditor.js?body=1:229 Uncaught TypeError: Cannot read property 'langEntries' of null
```

**Comment by ihinojal** [comment]
I'm also having this problema.

Anyway, it wont solve your problem, but IMHO you should add plugins like this:

`  config.extraPlugins = 'dialog,dialogui,clipboard,widget,codesnippet';`

**Comment by ihinojal** [comment]
Solved by not re-requiring ckeditor in application.js with `require_tree .`:

Move all the code in `app/assets/javascript` but `application.js` to a folder, for example `code/`, then change `require_tree .` for `require_tree ./code` inside `application.js`

Your structure should be something like:
```
ivan@z11:~/Development/vetaparket/app/assets/javascripts (master)$ ls .
application.js  ckeditor  code
ivan@z11:~/Development/vetaparket/app/assets/javascripts (master)$ cat application.js 
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require ckeditor/init
//= require_tree ./code
```

Inside the `code` folder there will be your custom .coffee and .js files

**Comment by abhishek77in** [comment]
@ihinojal doesn't look like the right thing to do. Can you explain why is it correct what you are doing ?

**Comment by ihinojal** [comment]
I had that problem and it was apparently was solved by doing that, but if you want a 'why', I have no idea why! Sorry buddy

**Comment by adityashedge** [comment]
I am using the word count plugin and I am not facing this issue. I have a 'en' lang file in the word count plugin directory (app/assets/javascripts/ckeditor/plugins/wordcount/lang/en.js) and in the application js file I have ```//= require ckeditor/init``` nothing else and I works correctly.
Don't have to ```require_tree``` or set ```config.setLang``` but I have set the ```assets_languages``` in the config.
```ruby
Ckeditor.setup do |config|
  config.assets_languages = ['en']
end
```

**Comment by n1ckp** [comment]
I was having the same 'langEntries' issues, it's to do with the order in which the ckeditor javascript files are loaded. The inspector errors in Chrome console point to the fact that `CKEDITOR.plugins.get('widget')` is returning `null` when called within the codesnippet languages files (there's a file for each language, hence why duplicate errors appear), so the widget plugin isn't getting loaded before the codesnippet plugin.

I resolved those errors by putting in my application.js:

```javascript
...
//= require ckeditor/init
//= require ckeditor/plugins/widget/plugin
//= require ckeditor/plugins/codesnippet/plugin
//= require ckeditor/config
//= require_tree .
...
```

However, I am still getting the error related to the `CKCONSOLE` object not being found. I know it's something to do with the widget plugin..

**Comment by safwan74** [comment]
What solved the problem for me is creating the en.js and then change the name of the library to match the name of your library in the library folder in the lang folder in this line number 3 CKEDITOR.plugins.setLang('tabscontainer', 'en', { # the rest of the code. 

tabscontainer is the name of my custom library.

**Comment by dnorthrupva** [comment]
I can confirm this is still an issue and n1ckp's recommendation resolves it. Find out which file is prompting the error and require it's plugin.js specifically.

**Comment by siddhantbajaj** [comment]
@n1ckp did you find any fix for `CKCONSOLE not defined`?

**Comment by JulienVerkest** [comment]
@siddhantbajaj If you remove assets/javascripts/ckeditor/plugins/widget/dev/ folder, the `CKCONSOLE not defined` doesn't appear anymore. 
Rails include all js files in config/initializers/assets.rb
```
Rails.application.config.assets.precompile += %w[
  ckeditor/*
]
```

**Comment by opkiler22789** [comment]
Please correct this! Or already there is a solution to this problem?

**Comment by mrluizandre** [comment]
@JulienVerkest Solved my `CKCONSOLE not defined` problem, it it doesn't come back again :D
